# Generated by Django 3.2.8 on 2021-10-14 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportMeet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('sport', models.CharField(choices=[('football', 'football'), ('basketball', 'basketball'), ('tennis', 'tennis')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeamPrivileges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_invite_new_members', models.BooleanField(blank=True, default=False)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SportMeet.profile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportMeet.team')),
            ],
        ),
    ]
