# Generated by Django 3.2.8 on 2021-10-23 09:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportMeet', '0003_auto_20211021_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GameField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250)),
                ('is_seen', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportMeet.profile')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adminteam', to='SportMeet.profile'),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, to='SportMeet.Profile'),
        ),
        migrations.DeleteModel(
            name='TeamPrivileges',
        ),
        migrations.AddField(
            model_name='game',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SportMeet.gamefield'),
        ),
        migrations.AddField(
            model_name='game',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportMeet.team'),
        ),
        migrations.AddField(
            model_name='appmessage',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportMeet.team'),
        ),
    ]
