# Generated by Django 3.2.8 on 2021-10-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportMeet', '0005_auto_20211026_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='team', to='SportMeet.Profile'),
        ),
    ]
