# Generated by Django 3.2.8 on 2021-11-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportMeet', '0007_alter_game_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('זכר', 'זכר'), ('נקבה', 'נקבה')], max_length=10),
        ),
    ]
