# Generated by Django 3.2.8 on 2022-01-04 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportMeet', '0008_alter_profile_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamefield',
            old_name='address',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='gamefield',
            old_name='city',
            new_name='telephone',
        ),
        migrations.AddField(
            model_name='appmessage',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appmessage',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SportMeet.profile'),
        ),
        migrations.AddField(
            model_name='gamefield',
            name='address_number',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamefield',
            name='availability',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamefield',
            name='is_for_basketball',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamefield',
            name='is_for_football',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamefield',
            name='is_for_tennis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamefield',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamefield',
            name='region',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='encrypted_email',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='type',
            field=models.CharField(choices=[('פומבית', 'פומבית'), ('פרטית', 'פרטית')], default='פרטית', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adminteam', to='SportMeet.profile'),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport',
            field=models.CharField(choices=[('כדורגל', 'כדורגל'), ('כדורסל', 'כדורסל'), ('טניס', 'טניס')], max_length=50),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('מגיע', 'מגיע'), ('לא מגיע', 'לא מגיע'), ('אולי מגיע', 'אולי מגיע')], max_length=10, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportMeet.game')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportMeet.profile')),
            ],
        ),
    ]
