# Generated by Django 3.2.8 on 2022-01-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportMeet', '0009_auto_20220104_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='encrypted_email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.BinaryField(null=True),
        ),
    ]
